#!/bin/sh

if [ 'WM_CLASS(STRING) = "emacs", "Emacs"' = "$(xprop WM_CLASS -id `pfw`)" ]; then
    case $1 in
      (0)
        xdotool key F31
        ;;
      (1)
        xdotool key F32
        ;;
      (2)
        xdotool key F33
        ;;
      (*)
        xdotool key F31
        ;;
    esac
else
  emxkb $1
fi
